### ISSUE TITLE
Do locks leak?

### ISSUE THREAD

**Issue by tomwhoiscontrary** [concourse/pool-resource#10]
In your example:

```
jobs:
- name: deploy-aws
  plan:
    - put: aws-environments
      params: {acquire: true}
    - task: deploy-aws
      file: my-scripts/deploy-aws.yml

- name: test-aws
  plan:
    - get: aws-environments
      passed: [deploy-aws]
    - task: test-aws
      file: my-scripts/test-aws.yml
    - put: aws-environments
      params: {release: aws-environments}
```

If deploy-aws fails, and does not trigger test-aws, does it release the lock? Asking for a friend.
