### ISSUE TITLE
No helpful output when private key provided requires password

### ISSUE THREAD

**Issue by jfrank-pivotal** [concourse/pool-resource#16]
To reproduce this issue, set the pipeline below and provide an SSH key that has a password in the `private_key` field.  It's pretty quick to set up a new lock repo and add the generated public key as a deploy key on the repo (make sure to grant it write access).  Then run the `acquire-lock` job.  It errors out with absolutely no output.  Obviously this wouldn't work since there's no way to provide a password -- I just discovered it when I pasted in the wrong key by mistake -- but we can hopefully save someone else the trouble by grepping their key for `ENCRYPTED` or something like that and printing an appropriate warning.

```yaml
---
jobs:
- name: acquire-lock
  public: true
  plan:
  - put: test-pool
    params: {acquire: true}

- name: release-lock
  public: true
  plan:
  - put: test-pool
    params: {acquire: test-pool}

resources:
- name: test-pool
  type: pool
  source:
    uri: git@github.com:<REDACTED>/test-pool-resource.git
    branch: master
    pool: test-pool
    private_key: <private key that requires a password>
```
