### ISSUE TITLE
Having trouble stabilizing a demonstration pipeline

### ISSUE THREAD

**Issue by hfinucane** [concourse/pool-resource#21]
I've been doing some testing to make sure that I could use this, but my demonstration tends to grind to a halt and stop working when I leave it alone for too long.

```
resources:
- name: demolock # Single pool, single file prepopulated in demo/unclaimed/
  type: pool
  source:
    uri: ssh://git@git/concourse-locks.git
    branch: master
    pool: demo
    private_key: {{SSH_PRIVATE_KEY}}
- name: tick
  type: time
  source: {interval: 5s} # I know, it doesn't actually go off this often

jobs:
- name: Step 1
  plan:
    - get: tick
      trigger: true
    - put: demolock
      params: {acquire: true}
    - task: hello-world
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: busybox}
        run:
          path: echo
          args:
          - hello world

- name: Step 2
  plan:
    - get: tick
      passed: ["Step 1"]
      trigger: true
    - get: demolock
      passed: ["Step 1"]
    - task: sleep
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: busybox}
        run:
          path: sleep
          args:
          - 1

- name: Step 3
  plan:
    - get: tick
      passed: ["Step 1"]
      trigger: true
    - get: demolock
      passed: ["Step 1"]
    - task: sleep
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: busybox}
        run:
          path: sleep
          args:
          - 1

- name: "Step 4"
  plan:
    - get: tick
      passed: ["Step 2", "Step 3"]
      trigger: true
    - get: demolock
      passed: ["Step 2", "Step 3"]
      trigger: true
    - put: demolock
      params: {release: "demolock"}
```

I _think_ that the best way to reproduce it is to prod the "tick" resource so that the builds come down in the wrong order. I've seen "Step 4" remain untriggered, but usually it bails out with `error: lock instance is no longer acquired` while the lock file is still in `demo/claimed/`. That said, generally starting it up and going for a coffee is good enough. If I drop the `get: tick` step in the "Step 4" plan, it never bails out with an error.
