### ISSUE TITLE
Claiming lock on .gitkeep file

### ISSUE THREAD

**Issue by shashwathi** [concourse/pool-resource#3]
We have a job which acquired lock on .gitkeep file and it failed to release the lock at end of pipeline. I have attached snippets for acquiring lock and error for releasing lock.
![screen shot 2015-08-12 at 10 23 32 am](https://cloud.githubusercontent.com/assets/9938926/9231329/838a9fc6-40dc-11e5-923f-764f5e211ef8.png)
![screen shot 2015-08-12 at 10 26 44 am](https://cloud.githubusercontent.com/assets/9938926/9231353/b0960172-40dc-11e5-98cf-22dabb91ec85.png)

**Comment by xoebus** [comment]
@shashwathi I think you're missing a passed constraint on this job referring to the job that acquired the lock?

**Comment by shashwathi** [comment]
@xoebus After looking at our config again, looks like we had an unnecessary `get` before the initial `put` + `acquire` (stars for emphasis). After removing this line things work as expected. Closing this out. 
```
- name: claim-a1-environment
  plan:
  - aggregate:
    - get: cf-mysql-release
      passed:
      # all bosh-lite pipelines
      - release-upgrade-environment
      - release-failover-environment
      - release-scaling-environment
      trigger: true
    - **get: aws-integration-environment**
  - put: aws-integration-environment
    params:
      acquire: true
```
