### ISSUE TITLE
basename: missing operand

### ISSUE THREAD

**Issue by elgohr** [concourse/pool-resource#54]
Introduced by https://github.com/concourse/pool-resource/commit/542a82c65f887db32af52e5cddc178cfbc73623b we got the following error with Concourse 6.3.0:
```
Cloning into '/tmp/build/get'...
d706a9f myJob build 163 unclaiming: development
fatal: ambiguous argument 'HEAD~1': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
basename: missing operand
Try 'basename --help' for more information.
```

We're using an ophan branch for tracking the pools.

# Workaround
Set `depth` manually to some bigger value
```
- get: development
  resource: env-pool
  params:
     depth: 30
```
```
- put: env-pool
  params: {release: development}
  get_params:
     depth: 30
```

# Possible Fix
Revert https://github.com/concourse/pool-resource/commit/542a82c65f887db32af52e5cddc178cfbc73623b

**Comment by rahulkj** [comment]
yeah please revert this

**Comment by vito** [comment]
Reverted and shipped as v1.1.2:

```yaml
resource_types:
- name: pool
  type: registry-image
  source: {repository: concourse/pool-resource, tag: 1.1.2}
```
